WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:root:{'leads': {'status': [{'id': 8298849, 'status_id': 68706394}]}}
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/bouquet/1
Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/catalog/views.py", line 72, in post
    payment_url = create_payment(new_order)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/yookassa.py", line 46, in create_payment
    response = Payment.create(request)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/payment.py", line 66, in create
    response = instance.client.request(HttpVerb.POST, path, None, headers, params_object)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/client.py", line 51, in request
    raw_response = self.execute(body, method, path, query_params, request_headers)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/client.py", line 82, in execute
    self.log_response(raw_response.content, self.get_response_info(raw_response), raw_response.headers)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/client.py", line 169, in get_response_info
    "raise_for_status": response.raise_for_status(),
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://api.yookassa.ru/v3/payments
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/vaso/settings.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/bouquet/1
Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/catalog/views.py", line 72, in post
    payment_url = create_payment(new_order)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/yookassa.py", line 46, in create_payment
    response = Payment.create(request)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/payment.py", line 66, in create
    response = instance.client.request(HttpVerb.POST, path, None, headers, params_object)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/client.py", line 51, in request
    raw_response = self.execute(body, method, path, query_params, request_headers)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/client.py", line 82, in execute
    self.log_response(raw_response.content, self.get_response_info(raw_response), raw_response.headers)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/yookassa/client.py", line 169, in get_response_info
    "raise_for_status": response.raise_for_status(),
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://api.yookassa.ru/v3/payments
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/vaso/settings.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/orders/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/bouquet/1
Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/catalog/views.py", line 54, in post
    profile = UserProfile.objects.get(user=request.user)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x744b89c2c370>>.
ERROR:django.request:Internal Server Error: /catalog/bouquet/1
Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/catalog/views.py", line 54, in post
    profile = UserProfile.objects.get(user=request.user)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x744b7a70a410>>.
ERROR:django.request:Internal Server Error: /catalog/bouquet/1
Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/catalog/views.py", line 54, in post
    profile = UserProfile.objects.get(user=request.user)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x744b881ddbd0>>.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/urls.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
INFO:django.utils.autoreload:/media/dmitry/892692f6-5784-45bf-99db-b9bc8507ff9d/dmitry/projects/vaso-site/vaso/user/views.py changed, reloading.
